# 2. Even Finbonacci Numbers
# Each new term in the Fibonacci sequence is generated by adding
# the previous two terms. By starting with 1 and 2, the first 10
# terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values
# do not exceed four million, find the sum of the even-valued terms.


# Solution 1

f1 = 0
f2 = 1

sum = 0
fib = 0

while fib < 4000000
	fib = f1 + f2
	f1 = f2
	f2 = fib
	sum += fib if fib % 2 == 0
end

# Solution 2

sum = 0
f1 = 0 
f2 = 1
while f2 < 4000000
	f2 = f1 + f2
	f1 = f2 - f1
	sum += f2 if f2 % 2 == 0
end
